version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sbctl
    main: ./cmd/sbctl/
    binary: sbctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: sbctl
    builds: [sbctl]
    name_template: "sbctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    formats: [tar.gz]

checksum:
  name_template: "checksum.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
