// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/account"
	"github.com/kilip/sbctl/ent/predicate"
	"github.com/kilip/sbctl/ent/session"
	"github.com/kilip/sbctl/ent/user"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *AccountUpdate) SetDeleted(v time.Time) *AccountUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDeleted(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *AccountUpdate) ClearDeleted() *AccountUpdate {
	_u.mutation.ClearDeleted()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUpdate) SetUserID(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUserID(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountUpdate) SetPlatform(v string) *AccountUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountUpdate) SetNillablePlatform(v *string) *AccountUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *AccountUpdate) SetExternalID(v string) *AccountUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableExternalID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdate) SetStatus(v account.Status) *AccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableStatus(v *account.Status) *AccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AccountUpdate) SetMetadata(v json.RawMessage) *AccountUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *AccountUpdate) AppendMetadata(v json.RawMessage) *AccountUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AccountUpdate) ClearMetadata() *AccountUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreated sets the "created" field.
func (_u *AccountUpdate) SetCreated(v time.Time) *AccountUpdate {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCreated(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AccountUpdate) SetUpdated(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdate) SetUser(v *User) *AccountUpdate {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *AccountUpdate) AddSessionIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *AccountUpdate) AddSessions(v ...*Session) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdate) ClearUser() *AccountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *AccountUpdate) ClearSessions() *AccountUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *AccountUpdate) RemoveSessionIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *AccountUpdate) RemoveSessions(v ...*Session) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := account.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(account.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(account.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(account.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(account.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(account.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, account.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(account.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(account.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(account.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetDeleted sets the "deleted" field.
func (_u *AccountUpdateOne) SetDeleted(v time.Time) *AccountUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDeleted(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *AccountUpdateOne) ClearDeleted() *AccountUpdateOne {
	_u.mutation.ClearDeleted()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUpdateOne) SetUserID(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUserID(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountUpdateOne) SetPlatform(v string) *AccountUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillablePlatform(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *AccountUpdateOne) SetExternalID(v string) *AccountUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableExternalID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdateOne) SetStatus(v account.Status) *AccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableStatus(v *account.Status) *AccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AccountUpdateOne) SetMetadata(v json.RawMessage) *AccountUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *AccountUpdateOne) AppendMetadata(v json.RawMessage) *AccountUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AccountUpdateOne) ClearMetadata() *AccountUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreated sets the "created" field.
func (_u *AccountUpdateOne) SetCreated(v time.Time) *AccountUpdateOne {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCreated(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AccountUpdateOne) SetUpdated(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdateOne) SetUser(v *User) *AccountUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *AccountUpdateOne) AddSessionIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *AccountUpdateOne) AddSessions(v ...*Session) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdateOne) ClearUser() *AccountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *AccountUpdateOne) ClearSessions() *AccountUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *AccountUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *AccountUpdateOne) RemoveSessions(v ...*Session) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := account.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(account.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(account.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(account.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(account.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(account.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, account.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(account.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(account.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(account.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
