// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/memory"
	"github.com/kilip/sbctl/ent/message"
	"github.com/kilip/sbctl/ent/predicate"
	"github.com/kilip/sbctl/ent/session"
	"github.com/kilip/sbctl/ent/user"
)

// MemoryUpdate is the builder for updating Memory entities.
type MemoryUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryMutation
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdate) Where(ps ...predicate.Memory) *MemoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoryUpdate) SetUserID(v uuid.UUID) *MemoryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableUserID(v *uuid.UUID) *MemoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryUpdate) SetSessionID(v uuid.UUID) *MemoryUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableSessionID(v *uuid.UUID) *MemoryUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MemoryUpdate) SetMessageID(v uuid.UUID) *MemoryUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableMessageID(v *uuid.UUID) *MemoryUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryUpdate) SetContent(v string) *MemoryUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableContent(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryUpdate) SetMetadata(v json.RawMessage) *MemoryUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MemoryUpdate) AppendMetadata(v json.RawMessage) *MemoryUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryUpdate) ClearMetadata() *MemoryUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *MemoryUpdate) SetEmbedding(v []byte) *MemoryUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *MemoryUpdate) ClearEmbedding() *MemoryUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetCreated sets the "created" field.
func (_u *MemoryUpdate) SetCreated(v time.Time) *MemoryUpdate {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableCreated(v *time.Time) *MemoryUpdate {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *MemoryUpdate) SetUpdated(v time.Time) *MemoryUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemoryUpdate) SetUser(v *User) *MemoryUpdate {
	return _u.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MemoryUpdate) SetSession(v *Session) *MemoryUpdate {
	return _u.SetSessionID(v.ID)
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *MemoryUpdate) SetMessage(v *Message) *MemoryUpdate {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdate) Mutation() *MemoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemoryUpdate) ClearUser() *MemoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MemoryUpdate) ClearSession() *MemoryUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *MemoryUpdate) ClearMessage() *MemoryUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := memory.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.user"`)
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.session"`)
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.message"`)
	}
	return nil
}

func (_u *MemoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memory.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(memory.FieldEmbedding, field.TypeBytes)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(memory.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(memory.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.SessionTable,
			Columns: []string{memory.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.SessionTable,
			Columns: []string{memory.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.MessageTable,
			Columns: []string{memory.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.MessageTable,
			Columns: []string{memory.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryUpdateOne is the builder for updating a single Memory entity.
type MemoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryMutation
}

// SetUserID sets the "user_id" field.
func (_u *MemoryUpdateOne) SetUserID(v uuid.UUID) *MemoryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableUserID(v *uuid.UUID) *MemoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryUpdateOne) SetSessionID(v uuid.UUID) *MemoryUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableSessionID(v *uuid.UUID) *MemoryUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MemoryUpdateOne) SetMessageID(v uuid.UUID) *MemoryUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableMessageID(v *uuid.UUID) *MemoryUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryUpdateOne) SetContent(v string) *MemoryUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableContent(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryUpdateOne) SetMetadata(v json.RawMessage) *MemoryUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MemoryUpdateOne) AppendMetadata(v json.RawMessage) *MemoryUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryUpdateOne) ClearMetadata() *MemoryUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *MemoryUpdateOne) SetEmbedding(v []byte) *MemoryUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *MemoryUpdateOne) ClearEmbedding() *MemoryUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetCreated sets the "created" field.
func (_u *MemoryUpdateOne) SetCreated(v time.Time) *MemoryUpdateOne {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableCreated(v *time.Time) *MemoryUpdateOne {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *MemoryUpdateOne) SetUpdated(v time.Time) *MemoryUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemoryUpdateOne) SetUser(v *User) *MemoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MemoryUpdateOne) SetSession(v *Session) *MemoryUpdateOne {
	return _u.SetSessionID(v.ID)
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *MemoryUpdateOne) SetMessage(v *Message) *MemoryUpdateOne {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdateOne) Mutation() *MemoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemoryUpdateOne) ClearUser() *MemoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MemoryUpdateOne) ClearSession() *MemoryUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *MemoryUpdateOne) ClearMessage() *MemoryUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdateOne) Where(ps ...predicate.Memory) *MemoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryUpdateOne) Select(field string, fields ...string) *MemoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Memory entity.
func (_u *MemoryUpdateOne) Save(ctx context.Context) (*Memory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdateOne) SaveX(ctx context.Context) *Memory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := memory.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.user"`)
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.session"`)
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.message"`)
	}
	return nil
}

func (_u *MemoryUpdateOne) sqlSave(ctx context.Context) (_node *Memory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Memory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memory.FieldID)
		for _, f := range fields {
			if !memory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memory.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(memory.FieldEmbedding, field.TypeBytes)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(memory.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(memory.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.SessionTable,
			Columns: []string{memory.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.SessionTable,
			Columns: []string{memory.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.MessageTable,
			Columns: []string{memory.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.MessageTable,
			Columns: []string{memory.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Memory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
