// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/memory"
	"github.com/kilip/sbctl/ent/message"
	"github.com/kilip/sbctl/ent/session"
	"github.com/kilip/sbctl/ent/user"
)

// MemoryCreate is the builder for creating a Memory entity.
type MemoryCreate struct {
	config
	mutation *MemoryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MemoryCreate) SetUserID(v uuid.UUID) *MemoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MemoryCreate) SetSessionID(v uuid.UUID) *MemoryCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *MemoryCreate) SetMessageID(v uuid.UUID) *MemoryCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MemoryCreate) SetContent(v string) *MemoryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *MemoryCreate) SetMetadata(v json.RawMessage) *MemoryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *MemoryCreate) SetEmbedding(v []byte) *MemoryCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *MemoryCreate) SetCreated(v time.Time) *MemoryCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableCreated(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *MemoryCreate) SetUpdated(v time.Time) *MemoryCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableUpdated(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryCreate) SetID(v uuid.UUID) *MemoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableID(v *uuid.UUID) *MemoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MemoryCreate) SetUser(v *User) *MemoryCreate {
	return _c.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_c *MemoryCreate) SetSession(v *Session) *MemoryCreate {
	return _c.SetSessionID(v.ID)
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *MemoryCreate) SetMessage(v *Message) *MemoryCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_c *MemoryCreate) Mutation() *MemoryMutation {
	return _c.mutation
}

// Save creates the Memory in the database.
func (_c *MemoryCreate) Save(ctx context.Context) (*Memory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryCreate) SaveX(ctx context.Context) *Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryCreate) defaults() {
	if _, ok := _c.mutation.Created(); !ok {
		v := memory.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := memory.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := memory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Memory.user_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Memory.session_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "Memory.message_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Memory.content"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Memory.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Memory.updated"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Memory.user"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Memory.session"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "Memory.message"`)}
	}
	return nil
}

func (_c *MemoryCreate) sqlSave(ctx context.Context) (*Memory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryCreate) createSpec() (*Memory, *sqlgraph.CreateSpec) {
	var (
		_node = &Memory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memory.Table, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeBytes, value)
		_node.Embedding = &value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(memory.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(memory.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.SessionTable,
			Columns: []string{memory.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.MessageTable,
			Columns: []string{memory.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoryCreateBulk is the builder for creating many Memory entities in bulk.
type MemoryCreateBulk struct {
	config
	err      error
	builders []*MemoryCreate
}

// Save creates the Memory entities in the database.
func (_c *MemoryCreateBulk) Save(ctx context.Context) ([]*Memory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryCreateBulk) SaveX(ctx context.Context) []*Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
