// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/memory"
	"github.com/kilip/sbctl/ent/message"
	"github.com/kilip/sbctl/ent/predicate"
	"github.com/kilip/sbctl/ent/session"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *MessageUpdate) SetDeleted(v time.Time) *MessageUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableDeleted(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *MessageUpdate) ClearDeleted() *MessageUpdate {
	_u.mutation.ClearDeleted()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdate) SetSessionID(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSessionID(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v message.Role) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *message.Role) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v json.RawMessage) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// AppendContent appends value to the "content" field.
func (_u *MessageUpdate) AppendContent(v json.RawMessage) *MessageUpdate {
	_u.mutation.AppendContent(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MessageUpdate) SetStatus(v message.Status) *MessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableStatus(v *message.Status) *MessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *MessageUpdate) SetTokenCount(v int) *MessageUpdate {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableTokenCount(v *int) *MessageUpdate {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *MessageUpdate) AddTokenCount(v int) *MessageUpdate {
	_u.mutation.AddTokenCount(v)
	return _u
}

// ClearTokenCount clears the value of the "token_count" field.
func (_u *MessageUpdate) ClearTokenCount() *MessageUpdate {
	_u.mutation.ClearTokenCount()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MessageUpdate) SetMetadata(v json.RawMessage) *MessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MessageUpdate) AppendMetadata(v json.RawMessage) *MessageUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MessageUpdate) ClearMetadata() *MessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreated sets the "created" field.
func (_u *MessageUpdate) SetCreated(v time.Time) *MessageUpdate {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCreated(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *MessageUpdate) SetUpdated(v time.Time) *MessageUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MessageUpdate) SetSession(v *Session) *MessageUpdate {
	return _u.SetSessionID(v.ID)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *MessageUpdate) AddMemoryIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *MessageUpdate) AddMemories(v ...*Memory) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MessageUpdate) ClearSession() *MessageUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *MessageUpdate) ClearMemories() *MessageUpdate {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *MessageUpdate) RemoveMemoryIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *MessageUpdate) RemoveMemories(v ...*Memory) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := message.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := message.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Message.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.session"`)
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(message.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(message.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldContent, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(message.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(message.FieldTokenCount, field.TypeInt, value)
	}
	if _u.mutation.TokenCountCleared() {
		_spec.ClearField(message.FieldTokenCount, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(message.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(message.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(message.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(message.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetDeleted sets the "deleted" field.
func (_u *MessageUpdateOne) SetDeleted(v time.Time) *MessageUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableDeleted(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *MessageUpdateOne) ClearDeleted() *MessageUpdateOne {
	_u.mutation.ClearDeleted()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdateOne) SetSessionID(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSessionID(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v message.Role) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *message.Role) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v json.RawMessage) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// AppendContent appends value to the "content" field.
func (_u *MessageUpdateOne) AppendContent(v json.RawMessage) *MessageUpdateOne {
	_u.mutation.AppendContent(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MessageUpdateOne) SetStatus(v message.Status) *MessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableStatus(v *message.Status) *MessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *MessageUpdateOne) SetTokenCount(v int) *MessageUpdateOne {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableTokenCount(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *MessageUpdateOne) AddTokenCount(v int) *MessageUpdateOne {
	_u.mutation.AddTokenCount(v)
	return _u
}

// ClearTokenCount clears the value of the "token_count" field.
func (_u *MessageUpdateOne) ClearTokenCount() *MessageUpdateOne {
	_u.mutation.ClearTokenCount()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MessageUpdateOne) SetMetadata(v json.RawMessage) *MessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MessageUpdateOne) AppendMetadata(v json.RawMessage) *MessageUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MessageUpdateOne) ClearMetadata() *MessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreated sets the "created" field.
func (_u *MessageUpdateOne) SetCreated(v time.Time) *MessageUpdateOne {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCreated(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *MessageUpdateOne) SetUpdated(v time.Time) *MessageUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MessageUpdateOne) SetSession(v *Session) *MessageUpdateOne {
	return _u.SetSessionID(v.ID)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *MessageUpdateOne) AddMemoryIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *MessageUpdateOne) AddMemories(v ...*Memory) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MessageUpdateOne) ClearSession() *MessageUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *MessageUpdateOne) ClearMemories() *MessageUpdateOne {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *MessageUpdateOne) RemoveMemoryIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *MessageUpdateOne) RemoveMemories(v ...*Memory) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := message.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := message.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Message.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.session"`)
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(message.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(message.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldContent, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(message.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(message.FieldTokenCount, field.TypeInt, value)
	}
	if _u.mutation.TokenCountCleared() {
		_spec.ClearField(message.FieldTokenCount, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(message.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(message.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(message.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(message.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.MemoriesTable,
			Columns: []string{message.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
