// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/predicate"
	"github.com/kilip/sbctl/ent/profile"
	"github.com/kilip/sbctl/ent/session"
	"github.com/kilip/sbctl/ent/user"
)

// ProfileUpdate is the builder for updating Profile entities.
type ProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileMutation
}

// Where appends a list predicates to the ProfileUpdate builder.
func (_u *ProfileUpdate) Where(ps ...predicate.Profile) *ProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *ProfileUpdate) SetDeleted(v time.Time) *ProfileUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableDeleted(v *time.Time) *ProfileUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *ProfileUpdate) ClearDeleted() *ProfileUpdate {
	_u.mutation.ClearDeleted()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProfileUpdate) SetUserID(v uuid.UUID) *ProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableUserID(v *uuid.UUID) *ProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProfileUpdate) SetName(v string) *ProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableName(v *string) *ProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWorkingDir sets the "working_dir" field.
func (_u *ProfileUpdate) SetWorkingDir(v string) *ProfileUpdate {
	_u.mutation.SetWorkingDir(v)
	return _u
}

// SetNillableWorkingDir sets the "working_dir" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableWorkingDir(v *string) *ProfileUpdate {
	if v != nil {
		_u.SetWorkingDir(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ProfileUpdate) SetIsDefault(v bool) *ProfileUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableIsDefault(v *bool) *ProfileUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetCreated sets the "created" field.
func (_u *ProfileUpdate) SetCreated(v time.Time) *ProfileUpdate {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *ProfileUpdate) SetNillableCreated(v *time.Time) *ProfileUpdate {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *ProfileUpdate) SetUpdated(v time.Time) *ProfileUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProfileUpdate) SetUser(v *User) *ProfileUpdate {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *ProfileUpdate) AddSessionIDs(ids ...uuid.UUID) *ProfileUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *ProfileUpdate) AddSessions(v ...*Session) *ProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (_u *ProfileUpdate) Mutation() *ProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProfileUpdate) ClearUser() *ProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *ProfileUpdate) ClearSessions() *ProfileUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *ProfileUpdate) RemoveSessionIDs(ids ...uuid.UUID) *ProfileUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *ProfileUpdate) RemoveSessions(v ...*Session) *ProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := profile.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Profile.user"`)
	}
	return nil
}

func (_u *ProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(profile.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(profile.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkingDir(); ok {
		_spec.SetField(profile.FieldWorkingDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(profile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(profile.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(profile.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfileUpdateOne is the builder for updating a single Profile entity.
type ProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileMutation
}

// SetDeleted sets the "deleted" field.
func (_u *ProfileUpdateOne) SetDeleted(v time.Time) *ProfileUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableDeleted(v *time.Time) *ProfileUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// ClearDeleted clears the value of the "deleted" field.
func (_u *ProfileUpdateOne) ClearDeleted() *ProfileUpdateOne {
	_u.mutation.ClearDeleted()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProfileUpdateOne) SetUserID(v uuid.UUID) *ProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableUserID(v *uuid.UUID) *ProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProfileUpdateOne) SetName(v string) *ProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableName(v *string) *ProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWorkingDir sets the "working_dir" field.
func (_u *ProfileUpdateOne) SetWorkingDir(v string) *ProfileUpdateOne {
	_u.mutation.SetWorkingDir(v)
	return _u
}

// SetNillableWorkingDir sets the "working_dir" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableWorkingDir(v *string) *ProfileUpdateOne {
	if v != nil {
		_u.SetWorkingDir(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ProfileUpdateOne) SetIsDefault(v bool) *ProfileUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableIsDefault(v *bool) *ProfileUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetCreated sets the "created" field.
func (_u *ProfileUpdateOne) SetCreated(v time.Time) *ProfileUpdateOne {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *ProfileUpdateOne) SetNillableCreated(v *time.Time) *ProfileUpdateOne {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *ProfileUpdateOne) SetUpdated(v time.Time) *ProfileUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProfileUpdateOne) SetUser(v *User) *ProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *ProfileUpdateOne) AddSessionIDs(ids ...uuid.UUID) *ProfileUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *ProfileUpdateOne) AddSessions(v ...*Session) *ProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (_u *ProfileUpdateOne) Mutation() *ProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProfileUpdateOne) ClearUser() *ProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *ProfileUpdateOne) ClearSessions() *ProfileUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *ProfileUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *ProfileUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *ProfileUpdateOne) RemoveSessions(v ...*Session) *ProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the ProfileUpdate builder.
func (_u *ProfileUpdateOne) Where(ps ...predicate.Profile) *ProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfileUpdateOne) Select(field string, fields ...string) *ProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Profile entity.
func (_u *ProfileUpdateOne) Save(ctx context.Context) (*Profile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileUpdateOne) SaveX(ctx context.Context) *Profile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := profile.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Profile.user"`)
	}
	return nil
}

func (_u *ProfileUpdateOne) sqlSave(ctx context.Context) (_node *Profile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profile.FieldID)
		for _, f := range fields {
			if !profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(profile.FieldDeleted, field.TypeTime, value)
	}
	if _u.mutation.DeletedCleared() {
		_spec.ClearField(profile.FieldDeleted, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkingDir(); ok {
		_spec.SetField(profile.FieldWorkingDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(profile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(profile.FieldCreated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(profile.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.SessionsTable,
			Columns: []string{profile.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
