// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/kilip/sbctl/ent/account"
	"github.com/kilip/sbctl/ent/auditlog"
	"github.com/kilip/sbctl/ent/memory"
	"github.com/kilip/sbctl/ent/message"
	"github.com/kilip/sbctl/ent/profile"
	"github.com/kilip/sbctl/ent/schema"
	"github.com/kilip/sbctl/ent/session"
	"github.com/kilip/sbctl/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreated is the schema descriptor for created field.
	accountDescCreated := accountFields[6].Descriptor()
	// account.DefaultCreated holds the default value on creation for the created field.
	account.DefaultCreated = accountDescCreated.Default.(func() time.Time)
	// accountDescUpdated is the schema descriptor for updated field.
	accountDescUpdated := accountFields[7].Descriptor()
	// account.DefaultUpdated holds the default value on creation for the updated field.
	account.DefaultUpdated = accountDescUpdated.Default.(func() time.Time)
	// account.UpdateDefaultUpdated holds the default value on update for the updated field.
	account.UpdateDefaultUpdated = accountDescUpdated.UpdateDefault.(func() time.Time)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreated is the schema descriptor for created field.
	auditlogDescCreated := auditlogFields[6].Descriptor()
	// auditlog.DefaultCreated holds the default value on creation for the created field.
	auditlog.DefaultCreated = auditlogDescCreated.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	memoryFields := schema.Memory{}.Fields()
	_ = memoryFields
	// memoryDescCreated is the schema descriptor for created field.
	memoryDescCreated := memoryFields[7].Descriptor()
	// memory.DefaultCreated holds the default value on creation for the created field.
	memory.DefaultCreated = memoryDescCreated.Default.(func() time.Time)
	// memoryDescUpdated is the schema descriptor for updated field.
	memoryDescUpdated := memoryFields[8].Descriptor()
	// memory.DefaultUpdated holds the default value on creation for the updated field.
	memory.DefaultUpdated = memoryDescUpdated.Default.(func() time.Time)
	// memory.UpdateDefaultUpdated holds the default value on update for the updated field.
	memory.UpdateDefaultUpdated = memoryDescUpdated.UpdateDefault.(func() time.Time)
	// memoryDescID is the schema descriptor for id field.
	memoryDescID := memoryFields[0].Descriptor()
	// memory.DefaultID holds the default value on creation for the id field.
	memory.DefaultID = memoryDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreated is the schema descriptor for created field.
	messageDescCreated := messageFields[7].Descriptor()
	// message.DefaultCreated holds the default value on creation for the created field.
	message.DefaultCreated = messageDescCreated.Default.(func() time.Time)
	// messageDescUpdated is the schema descriptor for updated field.
	messageDescUpdated := messageFields[8].Descriptor()
	// message.DefaultUpdated holds the default value on creation for the updated field.
	message.DefaultUpdated = messageDescUpdated.Default.(func() time.Time)
	// message.UpdateDefaultUpdated holds the default value on update for the updated field.
	message.UpdateDefaultUpdated = messageDescUpdated.UpdateDefault.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescIsDefault is the schema descriptor for is_default field.
	profileDescIsDefault := profileFields[4].Descriptor()
	// profile.DefaultIsDefault holds the default value on creation for the is_default field.
	profile.DefaultIsDefault = profileDescIsDefault.Default.(bool)
	// profileDescCreated is the schema descriptor for created field.
	profileDescCreated := profileFields[5].Descriptor()
	// profile.DefaultCreated holds the default value on creation for the created field.
	profile.DefaultCreated = profileDescCreated.Default.(func() time.Time)
	// profileDescUpdated is the schema descriptor for updated field.
	profileDescUpdated := profileFields[6].Descriptor()
	// profile.DefaultUpdated holds the default value on creation for the updated field.
	profile.DefaultUpdated = profileDescUpdated.Default.(func() time.Time)
	// profile.UpdateDefaultUpdated holds the default value on update for the updated field.
	profile.UpdateDefaultUpdated = profileDescUpdated.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreated is the schema descriptor for created field.
	sessionDescCreated := sessionFields[6].Descriptor()
	// session.DefaultCreated holds the default value on creation for the created field.
	session.DefaultCreated = sessionDescCreated.Default.(func() time.Time)
	// sessionDescUpdated is the schema descriptor for updated field.
	sessionDescUpdated := sessionFields[7].Descriptor()
	// session.DefaultUpdated holds the default value on creation for the updated field.
	session.DefaultUpdated = sessionDescUpdated.Default.(func() time.Time)
	// session.UpdateDefaultUpdated holds the default value on update for the updated field.
	session.UpdateDefaultUpdated = sessionDescUpdated.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreated is the schema descriptor for created field.
	userDescCreated := userFields[3].Descriptor()
	// user.DefaultCreated holds the default value on creation for the created field.
	user.DefaultCreated = userDescCreated.Default.(func() time.Time)
	// userDescUpdated is the schema descriptor for updated field.
	userDescUpdated := userFields[4].Descriptor()
	// user.DefaultUpdated holds the default value on creation for the updated field.
	user.DefaultUpdated = userDescUpdated.Default.(func() time.Time)
	// user.UpdateDefaultUpdated holds the default value on update for the updated field.
	user.UpdateDefaultUpdated = userDescUpdated.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
